name: Hello Workflow

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello Message
        run: echo "Hello from GitHub Actions!"
     
      - name: Print current date and time
        run: echo "Current date and time: $(date)"
      
      - name: List files in the repository
        run: ls -la
      
      - name: Print the branch name
        run: echo "Current branch: ${{ github.ref_name }}"
      
      - name: Print runner operating system
        run: echo "Runner operating system: ${{ runner.os }}"