name: This is my workflow

on:
  push:

jobs:
  personal-info:
    runs-on: ubuntu-latest
    steps:
      - name: Virat Kohli
        run: echo "Hie these I am virat Kohli"

      - name: Rohit Sharma
        run: echo "Hie there I am Rohit Sharma"
      
      - name: MS Dhoni
        run: echo "Hie there I am MS Dhoni"