name: Hello Greet Workflow

on:
  push

jobs:
  greet:
    runs-on: ubuntu-Latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Print Hello Greet
        run: echo "Hello Greet!"
